### ISSUE TITLE
Allow to specify the project folder like on the actual cli

### ISSUE THREAD

**Issue by ntrp** [Microsoft/Typedoc-Webpack-Plugin#14]
At the moment the **expandInputFiles** function have this value hard coded:

```
['./']
```

I think it is necessary to allow the user to pass in a custom array or string to modify the value..

A proposal would be changing the constructor to:

```
function TypedocWebpackPlugin(options, input) {
   this.inputFiles = ['./'];
   if (input) {
      this.inputFiles = (input.constructor === Array) ? input : [input];
   }
   ...
```

**Comment by timsawyer** [comment]
Pull request to resolve this is now approved
