### ISSUE TITLE
Allow JSON Output

### ISSUE THREAD

**Issue by jdolle** [Microsoft/Typedoc-Webpack-Plugin#16]
I would like to use Typedoc to generate JSON output on the fly through Webpack.

**Comment by timsawyer** [comment]
Hello, thanks for the feedback. I have now added support for the Typedoc "json" output property. Can you try out the latest version and let me know if this works for you:

typedoc-webpack-plugin@1.1.4

You can specify json output in your configuration with something like:

plugins: [
	new TypedocWebpackPlugin({
		name: 'Contoso'
		mode: 'file',
		json: './docs.json'
	})
]

**Comment by jdolle** [comment]
Fantastic! That works nicely. Thank you.

**Comment by timsawyer** [comment]
Great :)
